git config --global alias.pushall '!git remote | xargs -L1 git push --all'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias settings='XDG_CURRENT_DESKTOP=GNOME gnome-control-center &'
alias alice='/usr/bin/git --git-dir=$HOME/.alice/ --work-tree=$HOME'
alias btspeed='hcitool con | grep E6:6F:0C:E7:48:91 | awk '\''{print $5}'\'' | xargs -I{} sudo hcitool lecup --handle {} --min 6 --max 7 --latency 0'